# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Docker@2
  inputs:
    containerRegistry: 'Duckiehunt ACR'
    repository: 'azuredevops/duckiehunt'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: HelmDeploy@0
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 'duckiehunt-1-14-prod'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: 'charts/duckiehunt'
    releaseName: 'duckiehunt-prod'
    overrideValues: 'image.repository=duckiehunt.azurecr.io/azuredevops/duckiehunt,image.tag=$(Build.BuildId)'
    valueFile: 'charts/duckiehunt/values-prod.yaml'
    recreate: true