# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Docker@2
  inputs:
    containerRegistry: 'Duckiehunt ACR'
    repository: 'azuredevops/duckiehunt'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'v2.14.3'

- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'Visual Studio Enterprise (040eedd7-f236-48b7-8e04-5965674df326)'
    azureResourceGroup: 'duckiehunt'
    kubernetesCluster: 'duckiehunt-1-14'
    namespace: 'prod'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: 'charts/duckiehunt'
    releaseName: 'duckiehunt-prod'
    overrideValues: 'image.repository=duckiehunt.azurecr.io/azuredevops/duckiehunt,image.tag=$(Build.BuildId'
    valueFile: 'charts/duckiehunt/values-prod.yaml'
    recreate: true
