version: "3.4"
services:

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./data/mysql8/data:/var/lib/mysql
    ports:
      - "3306:3306"

  duckiehunt:
    build:
      context: .
    container_name: duckiehunt-local
    environment:
      - DJANGO_SETTINGS_MODULE=duckiehunt.settings.local
    volumes:
     - ./django:/code
    ports:
      - "80:8000/tcp"
    depends_on:
      - mysql

  duckiehunt-test:
    build:
      context: .
    container_name: duckiehunt-test
    environment:
      - DJANGO_SETTINGS_MODULE=duckiehunt.settings.local-test
    volumes:
     - ./django:/code
    ports:
      - "81:8000/tcp"
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
