version: "3"

services:
  duckiehunt:
    build:
      context: .
    container_name: duckiehunt
    volumes:
     - ./:/var/www/html
    ports:
      - "80:80"
    networks:
      - front-tier
      - back-tier
    environment:
      CI_BASE_URL: 'http://duckiehunt.local/'
      CI_DATABASE_HOSTNAME: 'db'
      CI_DATABASE_USERNAME: 'root'
      CI_DATABASE_PASSWORD: ''
      CI_DATABASE_DATABASE: 'duck_db'
      FLICKR_API_KEY: ${FLICKR_API_KEY}
      FLICKR_API_SECRET: ${FLICKR_API_SECRET}
      FLICKR_TOKEN: ${FLICKR_TOKEN}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      FLICKR_ACCESS_TOKEN: ${FLICKR_ACCESS_TOKEN}
      FLICKR_ACCESS_TOKEN_SECRET: ${FLICKR_ACCESS_TOKEN_SECRET}
      FLICKR_USER_NSID: ${FLICKR_USER_NSID}
      FLICKR_USER_NAME: ${FLICKR_USER_NAME}
      FLICKR_PERMISSIONS: ${FLICKR_PERMISSIONS}

  db:
    image: mysql
    container_name: db
    volumes:
      - "./docker-db:/var/lib/mysql"
    networks:
      - back-tier
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - "3306:3306"

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
