[environments]
  [environments.development]
    name = "duckiehunt-dev"
    namespace = "dev"
    wait = true
    watch = true
    auto-connect = false
    dockerfile = "Dockerfile"
    chart = "charts/duckiehunt"
    set = []
    registry = "duckiehunt.azurecr.io"