[environments]
  [environments.development]
    name = "duckiehunt-dev"
    namespace = "dev"
    wait = true
    watch = true
    watch-delay = 2
    auto-connect = false
    dockerfile = "Dockerfile"
    chart = ""
    registry = "duckiehunt.azurecr.io"
