{{- if .Values.ingress.clusterIssuer.enabled -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ .Values.ingress.clusterIssuer.name }}
spec:
  acme:
    server: {{ .Values.ingress.clusterIssuer.server }}
    email: {{ .Values.ingress.clusterIssuer.email }}
    privateKeySecretRef:
      name: {{ .Values.ingress.clusterIssuer.name }}
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end -}}