version: "3.4"
services:
  duckiehunt:
    build:
      context: ..
    container_name: duckiehunt-local
    environment:
      - DJANGO_SETTINGS_MODULE=duckiehunt.settings.local
    volumes:
     - ../django:/code
     - ../db:/db/
    ports:
      - "8000:8000/tcp"