version: "3.4"

services:

  # https://doc.traefik.io/traefik/user-guides/docker-compose/basic-example/
  # https://doc.traefik.io/traefik/user-guides/docker-compose/acme-http/
  traefik:
    image: traefik:2.8
    container_name: traefik
    restart: always
    network_mode: "host" # Needed to get other docker-compose in same host working
    command:
      - "--api.insecure=true"
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.admin.address=:8081"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=tommy@duckiehunt.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - /data/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /data/letsencrypt:/letsencrypt
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "8080:8080/tcp"
      - "8081:8081/tcp"
