services:
  prometheus:
    image: prom/prometheus
    volumes:
      - /data/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/etc/prometheus/tsdb'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    deploy:
      labels:
       - "traefik.http.routers.prometheus.service=prometheus"
       - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      restart_policy:
        condition: on-failure
    ports:
      - "9090:9090/tcp"
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    user: "nobody"
    volumes:
      - /data/grafana/data:/var/lib/grafana
      - /data/grafana/provisioning/:/etc/grafana/provisioning/
    deploy:
      labels:
        - "traefik.http.routers.grafana.service=grafana"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000/tcp"

