name: dh-prod
services:
  duckiehunt-prod:
    image: "duckiehunt.azurecr.io/gh/duckiehunt:latest"
    environment:
      - DJANGO_SETTINGS_MODULE=duckiehunt.settings.production
    volumes:
      - /data/duckiehunt-prod/settings:/code/duckiehunt/settings
      - /data/duckiehunt-prod/uploads:/code/uploads
      - /data/duckiehunt-stg/db:/db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.duckiehunt-prod.rule=Host(`duckiehunt.com`) || Host(`www.duckiehunt.com`)"
      - "traefik.http.routers.duckiehunt-prod.entrypoints=websecure"
      - "traefik.http.routers.duckiehunt-prod.tls.certresolver=myresolver"
      - "traefik.http.services.duckiehunt-prod.loadbalancer.server.port=8000"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s