name: dh-stg
services:
  duckiehunt-stg:
    image: ${DUCKIEHUNT_IMAGE}
    environment:
      - DJANGO_SETTINGS_MODULE=duckiehunt.settings.staging
    volumes:
      - /data/duckiehunt-stg/settings:/code/duckiehunt/settings
      - /data/duckiehunt-stg/db:/db
      - /data/duckiehunt-stg/uploads:/code/uploads
    labels:
      - "duckiehunt.env=staging"
      - "traefik.enable=true"
      - "traefik.http.routers.duckiehunt-stg.rule=Host(`stg.duckiehunt.com`)"
      - "traefik.http.routers.duckiehunt-stg.entrypoints=websecure"
      - "traefik.http.routers.duckiehunt-stg.tls.certresolver=myresolver"
      - "traefik.http.services.duckiehunt-stg.loadbalancer.server.port=8000"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1