name: dh-stg
services:
  duckiehunt-stg:
    image: "duckiehunt.azurecr.io/gh/duckiehunt:latest"
    environment:
      - DJANGO_SETTINGS_MODULE=duckiehunt.settings.staging
    volumes:
      - /data/duckiehunt-stg/settings:/code/duckiehunt/settings
      - /data/duckiehunt-stg/db:/db
      - /data/duckiehunt-stg/uploads:/code/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.duckiehunt-stg.rule=Host(`stg.duckiehunt.com`)"
      - "traefik.http.routers.duckiehunt-stg.entrypoints=websecure"
      - "traefik.http.routers.duckiehunt-stg.tls.certresolver=myresolver"
      - "traefik.http.services.duckiehunt-stg.loadbalancer.server.port=8000"