# Generated by Django 2.1 on 2018-09-01 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duck',
            fields=[
                ('duck_id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(blank=True)),
                ('name', models.CharField(blank=True, default=None, max_length=128)),
                ('comments', models.TextField(blank=True, default=None)),
                ('total_distance', models.FloatField(blank=True, default=0)),
                ('approved', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'duck',
            },
        ),
        migrations.CreateModel(
            name='DuckLocation',
            fields=[
                ('duck_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('flickr_photo_id', models.BigIntegerField(blank=True, null=True)),
                ('duck_history_id', models.IntegerField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('approved', models.CharField(blank=True, max_length=1, null=True)),
                ('distance_to', models.FloatField(blank=True, null=True)),
                ('duck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='duck.Duck')),
            ],
            options={
                'db_table': 'duck_location',
            },
        ),
        migrations.CreateModel(
            name='DuckLocationLink',
            fields=[
                ('duck_location_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('duck_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='duck.DuckLocation')),
            ],
            options={
                'db_table': 'duck_location_link',
            },
        ),
        migrations.CreateModel(
            name='DuckLocationPhoto',
            fields=[
                ('duck_location_photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('flickr_photo_id', models.BigIntegerField(blank=True, null=True)),
                ('flickr_thumbnail_url', models.TextField(blank=True, null=True)),
                ('duck_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='duck.DuckLocation')),
            ],
            options={
                'db_table': 'duck_location_photo',
            },
        ),
    ]
