# Generated by Django 6.0.5 on 2026-05-23 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duck', '0002_ducklocation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ducklocationlink',
            name='duck_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='duck.ducklocation'),
        ),
        migrations.AlterField(
            model_name='ducklocationphoto',
            name='duck_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='duck.ducklocation'),
        ),
    ]
