# Generated by Django 6.0.5 on 2026-05-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duck', '0004_add_duck_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ducklocation',
            name='date_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
