# Generated by Django 6.0.5 on 2026-05-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duck', '0005_add_date_time_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='ducklocationphoto',
            name='photo_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ducklocationphoto',
            name='photo_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ducklocationphoto',
            name='thumbnail_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
