# Generated by Django 6.0.5 on 2026-05-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duck', '0006_add_provider_agnostic_photo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ducklocationphoto',
            name='local_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
