from .client_tests import *
from .test_models import *
from .test_apis import *
from .test_views import *
from .test_marker import *
from .test_create_duck import *
from .test_mark_security import *
from .test_photo_upload import *
from .test_photo_providers import *
