replicaCount: 1

image:
  repository: duckiehunt.azurecr.io/duckiehunt
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: duckiehunt
  type: ClusterIP
  externalPort: 80
  internalPort: 8000

deployment:
  appConfigMountPath: /code/duckiehunt/secrets/
  imagesMountPath: /code/uploads/

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

volumes:
- name: app-config
  secret:
    secretName: duckiehunt-django
- name: images
  flexVolume:
    driver: "azure/blobfuse"
    readOnly: false
    secretRef:
      name: blobfusecreds
    options:
      container: prod
      tmppath: /tmp/blobfuse
      mountoptions: "--file-cache-timeout-in-seconds=120 --use-https=true"

env:
  ciBaseUrl: https://www.duckiehunt.com/

ingress:
  enabled: true
  host: www.duckiehunt.com
  clusterIssuer:
    # Assume this is enabled by the dev instance
    enabled: false
    name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tommy@lastcoolnameleft.com
  certificateName: prod-tls-secret
  rootRedirect:
    enabled: true
    redirectUrl: https://www.duckiehunt.com
    rootUrl: duckiehunt.com