name: Docker Image Build and Push

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: echo-default-env-variables
      run: |
          echo "Home: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_REF (env.): ${{ env.GITHUB_RUN_NUMBER }}"
          echo "GITHUB_REF: ${GITHUB_RUN_NUMBER}"



    - uses: azure/docker-login@v1
      with:
        login-server: duckiehunt.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build the Docker image        
      run: |
        docker build . -t duckiehunt.azurecr.io/gh/duckiehunt:${{ env.GITHUB_RUN_NUMBER }}
        docker push duckiehunt.azurecr.io/gh/duckiehunt:${{ env.GITHUB_RUN_NUMBER }}
