name: Docker Image Build and Push

env:
  CONTAINER_REGISTRY: ${{ secrets.REGISTRY_URL }}

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ master ]

jobs:

  build-push-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.CONTAINER_REGISTRY }}

    - name: Build the Docker image        
      run: |
        docker build . -t ${CONTAINER_REGISTRY}/gh/duckiehunt:${{ github.sha }}
        docker build . -t ${CONTAINER_REGISTRY}/gh/duckiehunt:latest
        docker push ${CONTAINER_REGISTRY}/gh/duckiehunt:${{ github.sha }}
        docker push ${CONTAINER_REGISTRY}/gh/duckiehunt:latest
