name: Docker Image Build and Push

env:
  CONTAINER_REGISTRY: ${{ secrets.REGISTRY_URL }}
  IMAGE_NAME: ${{ github.repository }}
  VM_DIR: /home/ghaction/duckiehunt
  IMAGE_TAG: ${{ github.head_ref || github.ref_name }}

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ master ]

jobs:

  build-push-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build the Docker image        
      run: |
        docker build . -t ${CONTAINER_REGISTRY}/gh/duckiehunt:${{ github.sha }}
        docker build . -t ${CONTAINER_REGISTRY}/gh/duckiehunt:latest
        docker push ${CONTAINER_REGISTRY}/gh/duckiehunt:${{ github.sha }}
        docker push ${CONTAINER_REGISTRY}/gh/duckiehunt:latest

  update-stg:
    name: Update VM (stg)
    runs-on: ubuntu-latest
    needs: build-push-deploy
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: copy docker compose via ssh
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "docker-compose/staging.yml,docker-compose/production.yml"
        target: /home/ghaction/duckiehunt/

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      if: github.event_name != 'pull_request'
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "Starting stg rollout"
          cd ${{ env.VM_DIR }}
          docker system prune -f
          docker pull ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker rollout -f docker-compose/staging.yml --env-file staging.env duckiehunt-stg