on: workflow_dispatch
name: Update Staging DB
env:
  VM_DIR: /home/ghaction/duckiehunt
jobs:
  update-db-stg:
    name: Update Staging DB
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@v1.0.3
      if: github.event_name != 'pull_request'
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script_stop: true
        script: |
          echo "Starting Staging DB update"
          cd ${{ env.VM_DIR }}
          CONTAINER_NAME=$(docker ps --filter "label=duckiehunt.env=staging" --format "{{json .Names }}" | tr -d '"')
          docker exec $CONTAINER_NAME python manage.py migrate